-- ====================================================
-- EUPHONY MUSIC APP - COMPLETE DATABASE SCHEMA
-- Run this in your new Supabase Project -> SQL Editor
-- ====================================================

-- 1. Songs Table
create table if not exists public.songs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  artist text not null,
  album text,
  lyrics text,
  url text not null,
  poster_url text,
  duration numeric,
  stem_vocals text,
  stem_drums text,
  stem_bass text,
  stem_other text,
  needs_stems boolean default false,
  created_at timestamptz default now()
);

-- 2. Artists Table
create table if not exists public.artists (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  image_url text,
  created_at timestamptz default now()
);

-- 3. Playlists Table
create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

-- 4. Playlist Songs Table (with foreign keys for nested relations)
create table if not exists public.playlist_songs (
  id bigint generated by default as identity primary key,
  playlist_id uuid references public.playlists(id) on delete cascade,
  song_id uuid references public.songs(id) on delete cascade,
  added_at timestamptz default now(),
  unique(playlist_id, song_id)
);

-- 5. Disable RLS (matches your current setup so all queries work immediately)
alter table public.songs disable row level security;
alter table public.artists disable row level security;
alter table public.playlists disable row level security;
alter table public.playlist_songs disable row level security;
